--- 
- name: testing Host_Var
  hosts: ClientVM01
  gather_facts: false
  become: true
  tasks: 
    - name: testing Host_Var
      user: 
       name: "{{name}}" 
       comment: "This is DevOps user"
       shell: /bin/ksh
       groups: Office
      
    - name: validation user
      shell: "id {{name}}"
      register: newuser
    
    - name: printing value
      debug: 
          msg: "newuser.stdout"
    
...
