- name: install multiple stuff
  hosts: web
  tasks:
  - name: multiple stuff
    user:
      name: "{{item}}"
      state: present
    loop:
    - zip
    - unzip
    - tree
    - httpd
    - nfs-utils
   
