---
- name: Setting up NFS server
  hosts: web
  gather_facts: false
  become: true
  vars: 
     - name: diskname
       prompt: "what is your diskname ?"
       private: no
     
     - name: dir_path
       prompt: "what is your dir_path name ?"
       private: no

  tasks:
  - name: first installing packages
    yum: 
     name: nfs-utils 
     state: present
    
  - name: Creating new file system for NFS mount. 
    filesystem: 
       dev: "{{diskname}}"
       fstype: ext4
   
  - name: Create Directory
    file: 
       path: "{{dir_path}}"
       state: directory
       mode: "0777"

  - name: mount partition
    mount:
       path: "{{dir_path}}"
       src: "{{diskname}}"
       fstype: ext4
       state: mounted 

  - name: Create entry at /etc/fstab for file system.
    command: |
        echo "{{diskname}} {{dir_path}} xfs defaults 0 0" >> /etc/fstab

