- name: Configure network
  hosts: web
  become: true
  tasks:
  - name: Configure network interface
    nmcli:
      name: enp0s3
      method: static
      ipaddr: 192.168.48.150
      netmask: 255.255.255.0
      gateway: 192.168.48.2
      state: present
