- name: Configure network
  hosts: node1
  become: true
  vars:
    interface: enp0s3
    method: static
    ipaddr: 192.168.48.150
    netmask: 255.255.255.0
    gateway: 192.168.48.2
  tasks:
  - name: Configure network interface
    network_interface:
      name: "{{ interface }}"
      state: up
      method: "{{ method }}"
      ipaddr: "{{ ipaddr }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"

