- name: Configure network
  hosts: web
  gather_facts: false
  become: true
  vars_prompt:

  - name: conname
    prompt: "please enter the connection name?"
    private: no

  - name: myip4
    prompt: "what ip4 would you like to add?"
    private: no

  tasks:
  - name: Configuring network interface
    nmcli:
      conn_name: "{{conname}}"
      ifname: ens160
      type: ethernet
      ip4: "{{ myip4 }}"
      gw4: 192.168.48.2
      state: present
      autoconnect: yes

  - name: displaying list of connections.
    command: "nmcli con show"
    register: displaycon

  - name: displaying connections on host.
    debug:
      var: displaycon.stdout_lines


