- name: Configure network
  hosts: web
  gather_facts: false
  become: true
  tasks:
  - name: Configure network interface
    nmcli:
     conn_name: mycon007 
     ifname: ens160
     type: ethernet 
     ip4: 192.168.48.175/24 
     gw4: 192.168.48.2
     state: present
