---
- name: 
  hosts: all
  tasks: 
    
    - name: prestep 01
      command: yum clean all
   
    - name: prestep 02
      command: yum clean metadata
    
    - name: prestep 03
      command: rm-rf /var/cache/yum/*
      command: subscription-manager repos --list
      command: yum repolist
 
    - name: patching servers
      yum:
        name: '*'
        state: latest
        
    - debug: 
        msg: "servers have been patched" 

- hosts: web
  tasks:
    - name: rebooting severs
      reboot:
       reboot_timeout: 1800 
       test_command: uptime

    - name: WHO AM I 
      command: whoami
      register: myname  
       
    - name: display WHO AM I
      debug: msg="{{ myname.stdout_lines }}"



... 
