---
- name: testing templete module
  hosts: all
  tasks: 
    - name: adding text file
      template: 
             src: /root/test-projects/ansible-project/sampletamplete.j2
             dest: /etc/motd
      become: true 
